{% set version = "0.3.0" %}

package:
  name: grequests
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/grequests/grequests-{{ version }}.tar.gz
  sha256: 0f41c4eee83bab39f5543af49665c08681637a0562a5704a3f7b2e4a996531c9

build:
  number: 1
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - python
    - gevent
    - requests

test:
  imports:
    - grequests

about:
  home: https://github.com/kennethreitz/grequests
  license: BSD 3-Clause
  # license_file: No MANIFEST included in package - see https://github.com/kennethreitz/grequests/issues/95
  license_family: BSD
  summary: 'Requests + Gevent'

extra:
  recipe-maintainers:
    - pmlandwehr
