# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "Hi2pbq8Vx68PBaTLhn9zxWMkpmeQ7xyyx7LlEqB+tqAROexKThdgcuOvE6Lsrwr9Sh3sLu/gyVLieZMJjaXIJxY7xSiFx5lC9fEltikvZvL5yVAxnKeqUHe3lU4N+MNhLZ1hOq2mfm3Avi01OHai6E8K9mtPWPCX6vRKiMiQq/Lhaf1+lBjjah8k1bUr+fCnIfJOrkkoJaPDbilpgbzKeYkz5fdjJWNtM1OJr61G3oC4cvYmWRZgSAHFNZqDN0rrhT4w3FUZIClqsCMyUz+nw5eJAN6/eSRRc87h79Y2xY1tzSTgV/jsGk3V1FSbowtJp7NH53ISQsL6Q9boHNBfu+HMRDculy7Bnzd39pECWOj2TZwlGzz7FzCh1lCMv0HEOFhxJbx6deJ9vvPhtm7Ro8hqnL0IaQNBWoEZNVsUKaGvO9BVzxx7ReokiytuioKXN4iQCzddAE1Abc/mnAVQO8ZaHEerlZStkvJLu14E/UFdAdRLLaEgazVydbFsPyopFqAZQHw3PSueM97ucmkFQhRvKwu4kUFMN/VIEkLzQL5BiPGTv5u9GQ8a+kiigYmjwolrcPCLoDnvTVCcFriU7YZy3kVoHLhaSVeELwB5WarCFhd5NThigWWTxRRkLl5gR32clEzsFFEM3/kaXuuJAqxKzjggcPoxqxvlepGJKIw="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
