travis:
  secure:
    BINSTAR_TOKEN: Up7nQLugDYE/SUwsIXBHTma5cdHrhzTjXi9XZO3xByft/FEEIvbN2uJ0Yi8zlu/R1xZiL+V/mSNRz2iEje3mNlaq89vegpUnm8COFvr8BehGEnx7sp29Csnbi7D2NaVd12YcvCswMAXGkS2ML1XsChvHQfw1Ol8jphQCBbJE5GDiAu/hi2r1RVmpYLIYA+WdErCJxMNHbKVXlnacONxlj/EBlweUS224QPjpfSsIagGL3Fq9/iDcxdO1aekHBfw1MWLAu8lQShL24rF2wKkyHK4PdP22G9JdenTdMQVD0jmFalnzqambln2KJBx1mBvQFq9L/0vcTmK1qgJykOgUdTHU5/mrazhXVhN5ZD123GjWULq2mDCdYFCxk8vwSX3+ud8hDGxmhoDN0Xu/+vyn7wzQld5G5GWWckQB9ll69QoB0LUyXF0ZGDKYMx4X/uTCRdt/C6JU7wySIZ3MuAJSzJnoA336j7Nxmhco/oPMu7/GaORz6/wgZnEMpByF/9Xld3NFl8/VQAxmlGc14TTQkYaBfaA+EQPfvD4ODQHSrQ3MUa8rUvAyzCJuAWGoUHHINUuKOah2Ix5LgNpqfe18cmEuZQeE3KntJT2xu499coYOQzG9yRGzNhLqEVwSupUtWizxBCKFGSTKQAT+3xFRATTyWx+ewjjjHs2vggOtMdY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
