travis:
  secure:
    BINSTAR_TOKEN: KX4DpqNyj/sqpjhfUZeYg0nduQoyowy89LX1N1JcikoSXdF4+e+S6XIN7HEfCNK3Ne4X/ivOqLICX5CNIQgfALv2AsX1In/p4SBCY9nRNayYLa6/itw1Mrn5DCZ1J1Kdw0Dhrjsw0BBFQXtbbT5+0d6V4vB8h4C0EU3wxh8jt87geSM7lSCkYpjyqHPZbHWPrrYsvkwC0P1L6MMd8PVS6l9jdin3cgVuuzMnmcJSWItiE+GL3lFYEh8CUMCn9vJVZsZXgryiXkKAjN/JRw8ZmVpX+htjBnME+iBaXbU4gjL4yMcLb0tjHWVLC//JZ8ZE5A0sTDP/MG9AalfMk0gvLMQA+QNnAN7WqpiHCmGs9VxLwjaYfzvtZTkjDm6QBP52t/wDvHWTKCw6WZzG+iIAF4wKz5JviF1aX/BvQ0sYY/WupdmPun3x3krjNR0ltA7OI7MdOAkfxMUlzTi1NLd4iw9uXzfUb2Tgzo1cXas/bwuz1THCqzoTLLHCr3vCYbz7ZAhmTOsMYXtcFdxZ+P6/xEAZ0la5nPh1wTjsCHwYvKRKPYTQJb3jyECCmWxIa1lRRucOnV/3YC5QEyx9iPyiMI7iJY7Swt2ekisZSjheIDHhmj2Lju44hxpCPo9R8gY6g6Zq4Od0zB9KTlIQHqv5CPqN2wsXZ3Gu9e5q3WeLvDE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
